AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a public S3 website

Resources:
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: YOUR-BUCKET-NAME
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Environment
          Value: PublicWebsite

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${S3WebsiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: The URL of the S3 bucket website
    Value: !GetAtt S3WebsiteBucket.WebsiteURL
